<a href="https://colab.research.google.com/github/ajaykumar080286/feature_engineering/blob/main/10_ordinal_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder

In [64]:
df=pd.read_csv("https://raw.githubusercontent.com/ajaykumar080286/feature_engineering/main/customer.csv")

In [65]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [66]:
df=df.iloc[:,2:5]

In [67]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [68]:
X=df.iloc[:,0:2]
y=df.iloc[:,-1]

In [69]:
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2,random_state=0)

In [70]:
oc=OrdinalEncoder(categories=[["Poor","Good","Average"],["School","UG","PG"]])

In [71]:
oc.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Good', 'Average'], ['School', 'UG', 'PG']])

In [72]:
X_train_trans=oc.transform(X_train)
X_test_trans=oc.transform(X_test)

In [73]:
X_train_trans=pd.DataFrame(X_train_trans,columns=X_train.columns)

In [89]:
X_train_trans.head(2)

   review  education
0     1.0        2.0
1     0.0        0.0

In [75]:
X_test_trans=pd.DataFrame(X_test_trans,columns=X_train.columns)

In [76]:
X_test_trans

   review  education
0     0.0        0.0
1     1.0        1.0
2     1.0        1.0
3     1.0        2.0
4     1.0        2.0
5     0.0        2.0
6     1.0        0.0
7     0.0        0.0
8     0.0        2.0
9     2.0        1.0

**Label Encoding**

In [77]:
le=LabelEncoder()

In [81]:
le.fit(y_train)

LabelEncoder()

In [83]:
y_train_trans=le.transform(y_train)

In [84]:
y_test_trans=le.transform(y_test)

In [85]:
y_test_trans

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 0])

In [87]:
y_train_trans

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [88]:
le.classes_

array(['No', 'Yes'], dtype=object)