<a href="https://colab.research.google.com/github/ajaykumar080286/feature_engineering/blob/main/12_one_hot_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/ajaykumar080286/feature_engineering/main/cars.csv")

In [3]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [4]:
df["owner"].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [5]:
df["owner"].nunique()

5

In [6]:
df["fuel"].nunique()

4

***1. OneHotEncoding using Pandas***

In [7]:
pd.get_dummies(df, columns=["fuel","owner"])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

**2. K-1 OneHotEncoding**

In [8]:
pd.get_dummies(df, columns=["fuel","owner"],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

***3. OneHotEncoding using Sklearn***

In [9]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [10]:
X=df.iloc[:,0:4]
y=df.iloc[:,-1]

In [11]:
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2, random_state=0)

In [44]:
ohe=OneHotEncoder(drop="first",sparse_output=False)

In [45]:
X_train_new=ohe.fit_transform(X_train[["fuel","owner"]])
#ohe=OneHotEncoder(sparse_output=False)
#X_train_new=ohe.fit_transform(X_train[["fuel","owner"]]).toarray()

In [46]:
X_train_new

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [47]:
df1=np.hstack((X_train[["brand","km_driven"]].values,X_train_new))

In [48]:
df1

array([['Hyundai', 60000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Tata', 150000, 1.0, ..., 0.0, 0.0, 1.0],
       ['Hyundai', 110000, 1.0, ..., 1.0, 0.0, 0.0],
       ...,
       ['Hyundai', 90000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Volkswagen', 90000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 110000, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [49]:
df2=pd.DataFrame(df1)

In [50]:
df2

               0       1    2    3    4    5    6    7    8
0        Hyundai   60000  0.0  1.0  0.0  0.0  0.0  0.0  0.0
1           Tata  150000  1.0  0.0  0.0  0.0  0.0  0.0  1.0
2        Hyundai  110000  1.0  0.0  0.0  0.0  1.0  0.0  0.0
3       Mahindra   28000  1.0  0.0  0.0  0.0  1.0  0.0  0.0
4         Maruti   15000  0.0  0.0  1.0  0.0  0.0  0.0  0.0
...          ...     ...  ...  ...  ...  ...  ...  ...  ...
6497        Tata   70000  1.0  0.0  0.0  0.0  0.0  0.0  1.0
6498        Ford  100000  1.0  0.0  0.0  0.0  1.0  0.0  0.0
6499     Hyundai   90000  0.0  0.0  1.0  0.0  1.0  0.0  0.0
6500  Volkswagen   90000  1.0  0.0  0.0  0.0  0.0  0.0  0.0
6501     Hyundai  110000  0.0  0.0  1.0  0.0  0.0  0.0  0.0

[6502 rows x 9 columns]

***4. OneHotEncoding with Top Categories***

In [51]:
counts=df["brand"].value_counts()

In [52]:
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [53]:
df['brand'].nunique()

32

In [54]:
threshold = 100

In [66]:
repl = counts[counts <= threshold].index

In [67]:
repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [69]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'), dtype=int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
5618,0,0,0,0,0,0,0,0,0,0,0,0,1
6374,0,0,0,0,0,0,1,0,0,0,0,0,0
4816,0,0,0,0,0,0,0,0,0,0,0,0,1
927,0,0,0,0,0,0,0,0,0,1,0,0,0
1752,0,0,0,0,0,1,0,0,0,0,0,0,0