<a href="https://colab.research.google.com/github/ajaykumar080286/feature_engineering/blob/main/13_column_transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [121]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [102]:
df=pd.read_csv("https://raw.githubusercontent.com/ajaykumar080286/feature_engineering/main/covid_toy.csv")

In [103]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [104]:
df["cough"].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [105]:
X=df.iloc[:,0:5]
y=df.iloc[:,-1]

In [106]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2, random_state=0)

***Simple Imputer-Missing Values***

In [107]:
imp=SimpleImputer()

In [108]:
X_train_tf1=imp.fit_transform(X_train[["fever"]])
X_test_tf1=imp.transform(X_test[["fever"]])

***OrdinalEncoder***

In [109]:
ode=OrdinalEncoder(categories=[["Mild","Strong"]])

In [110]:
X_train_tf2=ode.fit_transform(X_train[["cough"]])
X_test_tf2=ode.transform(X_test[["cough"]])

**OneHotEncoding**

In [111]:
ohe=OneHotEncoder(drop="first", sparse_output=False)

In [112]:
X_train_tf3=ohe.fit_transform(X_train[["gender","city"]])
X_test_tf3=ohe.transform(X_test[["gender","city"]])

In [113]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [114]:
X_train_tf4=X_train.drop(columns=["gender","fever", "cough","city"]).values
X_test_tf4=X_test.drop(columns=["gender","fever", "cough","city"]).values

In [115]:
X_train_transformed=np.concatenate((X_train_tf4, X_train_tf1, X_train_tf3,X_train_tf2),axis=1)
X_test_transformed=np.concatenate((X_test_tf4, X_test_tf1, X_test_tf3,X_test_tf2),axis=1)

In [116]:
X_test_transformed.shape

(20, 7)

**Label Encoding**

In [117]:
lbe=LabelEncoder()

In [118]:
y_train=lbe.fit_transform(y_train)
y_test=lbe.transform(y_test)

In [120]:
y_test

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0])

In [126]:
X_train

    age  gender  fever   cough       city
43   22  Female   99.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
3    31  Female   98.0    Mild    Kolkata
71   75  Female  104.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
96   51  Female  101.0  Strong    Kolkata
67   65    Male   99.0    Mild  Bangalore
64   42    Male  104.0    Mild     Mumbai
47   18  Female  104.0    Mild  Bangalore
44   20    Male  102.0  Strong      Delhi

[80 rows x 5 columns]

**Column Transformer**

In [131]:
columntrans=ColumnTransformer(
    transformers=[
        ("trf1", SimpleImputer(),["fever"]),
        ("trf2", OrdinalEncoder(categories=[["Mild","Strong"]]),["cough"]),
        ("trf3", OneHotEncoder(drop="first", sparse_output=False), ["gender","city"])

    ]
    ,remainder="passthrough"
    )

In [133]:
X_trains_trf=columntrans.fit_transform(X_train)
X_test_trf=columntrans.transform(X_test)

In [134]:
X_trains_trf.shape

(80, 7)

In [135]:
X_test_trf.shape

(20, 7)