<a href="https://colab.research.google.com/github/ajaykumar080286/feature_engineering/blob/main/1_Working_With_CSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

**Opening CSV file using CSV**

In [2]:
df=pd.read_csv("placement (1).csv")

In [3]:
df.head(5)

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

**3. Opening a csv file from an URL**

In [7]:
import pandas as pd

# Example: CSV file hosted online
url = "https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv"

# Read CSV from URL
df = pd.read_csv(url)

df.head()

   Index   Height(Inches)"   "Weight(Pounds)"
0      1             65.78             112.99
1      2             71.52             136.49
2      3             69.40             153.03
3      4             68.22             142.34
4      5             67.79             144.30

In [8]:
import requests
from io import StringIO

url = "https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

     Index   Height(Inches)"   "Weight(Pounds)"
0        1             65.78             112.99
1        2             71.52             136.49
2        3             69.40             153.03
3        4             68.22             142.34
4        5             67.79             144.30
..     ...               ...                ...
195    196             65.80             120.84
196    197             66.11             115.78
197    198             68.24             128.30
198    199             68.02             127.47
199    200             71.39             127.88

[200 rows x 3 columns]

In [13]:
# URL of the CSV file
url = "https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv"

# Fetch the file using requests
response = requests.get(url)

# Check if request was successful
if response.status_code == 200:
    # Convert the response text into a file-like object
    csv_data = StringIO(response.text)

    # Read into pandas DataFrame
    df = pd.read_csv(csv_data)

    print(df.head())
else:
    print("Failed to fetch CSV file. Status code:", response.status_code)

   Index   Height(Inches)"   "Weight(Pounds)"
0      1             65.78             112.99
1      2             71.52             136.49
2      3             69.40             153.03
3      4             68.22             142.34
4      5             67.79             144.30