<a href="https://colab.research.google.com/github/ajaykumar080286/feature_engineering/blob/main/21_handling_date_and_time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [37]:
date=pd.read_csv("https://raw.githubusercontent.com/ajaykumar080286/feature_engineering/main/orders.csv")
time=pd.read_csv("https://raw.githubusercontent.com/ajaykumar080286/feature_engineering/main/messages.csv")

In [38]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [39]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [40]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [41]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [42]:
date["date"]=pd.to_datetime(date["date"])

In [43]:
date.head()

        date  product_id  city_id  orders
0 2019-12-10        5628       25       3
1 2018-08-15        3646       14     157
2 2018-10-23        1859       25       1
3 2019-08-17        7292       25       1
4 2019-01-06        4344       25       3

In [44]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

***1. Extract year***

In [45]:
date["date_year"]=date["date"].dt.year

In [46]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

***2. Extract Month***

In [47]:
date["date_month"]=date["date"].dt.month

In [48]:
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month
511 2018-12-02        1403       29       3       2018          12
538 2018-08-24        4885       16      25       2018           8
606 2018-11-24        2870       25       8       2018          11
944 2019-07-26        4439        2      24       2019           7
935 2019-10-30        1931        0      57       2019          10

In [49]:
date["date_month_name"]=date["date"].dt.month_name()

In [50]:
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name
243,2019-11-29,5939,14,183,2019,11,November
31,2018-10-01,7386,3,1,2018,10,October
919,2019-06-01,6386,2,1,2019,6,June
658,2018-09-18,5266,22,1,2018,9,September
328,2019-11-20,7467,23,2,2019,11,November

In [51]:
date["date_day"]=date["date"].dt.day

In [52]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [53]:
date["date_day_week"]=date["date"].dt.day_of_week

In [54]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_week
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [55]:
date['date_dow_name'] = date['date'].dt.day_name()

In [56]:
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_week,date_dow_name
176,2018-12-16,1475,16,8,2018,12,December,16,6,Sunday
544,2018-08-01,3222,25,7,2018,8,August,1,2,Wednesday
380,2019-08-10,1005,14,1,2019,8,August,10,5,Saturday
645,2019-02-11,6091,25,40,2019,2,February,11,0,Monday
47,2018-12-11,3437,14,2,2018,12,December,11,1,Tuesday

In [57]:
date["date_is_weekend"]=np.where(date["date_dow_name"].isin(['Sunday', 'Saturday']),1,0)
date.drop(columns=["product_id","city_id","orders"])

,date,date_year,date_month,date_month_name,date_day,date_day_week,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1
...,...,...,...,...,...,...,...,...
995,2018-10-08,2018,10,October,8,0,Monday,0
996,2018-12-06,2018,12,December,6,3,Thursday,0
997,2019-05-07,2019,5,May,7,1,Tuesday,0
998,2019-03-03,2019,3,March,3,6,Sunday,1
999,2019-10-15,2019,10,October,15,1,Tuesday,0

**Extract week of the year**

In [58]:
date["date_week"]=date["date"].dt.isocalendar().week

In [59]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_week,date_dow_name,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

In [60]:
date["quater"]=date["date"].dt.quarter

In [61]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_week,date_dow_name,date_is_weekend,date_week,quater
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

***Extract Semester***

In [62]:
date['semester'] = np.where(date['quater'].isin([1,2]), 1, 2)

In [63]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_week,date_dow_name,date_is_weekend,date_week,quater,semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1

**Extract Time elapsed between dates**

In [64]:
import datetime

In [65]:
today=datetime.datetime.today()

In [66]:
today

datetime.datetime(2026, 3, 6, 17, 25, 17, 101716)

In [67]:
today - date['date']

0     2278 days 17:25:17.101716
1     2760 days 17:25:17.101716
2     2691 days 17:25:17.101716
3     2393 days 17:25:17.101716
4     2616 days 17:25:17.101716
                 ...
995   2706 days 17:25:17.101716
996   2647 days 17:25:17.101716
997   2495 days 17:25:17.101716
998   2560 days 17:25:17.101716
999   2334 days 17:25:17.101716
Name: date, Length: 1000, dtype: timedelta64[ns]

In [68]:
(today - date['date']).dt.days

0      2278
1      2760
2      2691
3      2393
4      2616
       ...
995    2706
996    2647
997    2495
998    2560
999    2334
Name: date, Length: 1000, dtype: int64

In [78]:
# Months passed

# Calculate the difference in days and divide by the average number of days in a month
#np.round((today - date['date']).dt.days / 30.44, 0)

In [70]:
time['date'] = pd.to_datetime(time['date'])

In [71]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [72]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [73]:
time['time'] = time['date'].dt.time

In [74]:
today - time['date']

0     4464 days 16:35:17.101716
1     4328 days 17:45:17.101716
2     4814 days 17:04:17.101716
3     4116 days 16:54:17.101716
4     4513 days 18:14:17.101716
                 ...
995   5103 days 16:35:17.101716
996   4424 days 18:11:17.101716
997   4889 days 17:48:17.101716
998   5005 days 17:51:17.101716
999   4277 days 18:00:17.101716
Name: date, Length: 1000, dtype: timedelta64[ns]

In [75]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.857493e+08
1      3.740031e+08
2      4.159911e+08
3      3.556833e+08
4      3.899889e+08
           ...
995    4.409589e+08
996    3.822991e+08
997    4.224737e+08
998    4.324963e+08
999    3.695976e+08
Name: date, Length: 1000, dtype: float64

In [76]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.429155e+06
1      6.233385e+06
2      6.933184e+06
3      5.928054e+06
4      6.499814e+06
           ...
995    7.349315e+06
996    6.371651e+06
997    7.041228e+06
998    7.208271e+06
999    6.159960e+06
Name: date, Length: 1000, dtype: float64

In [77]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      107152.588084
1      103889.754750
2      115553.071417
3       98800.904750
4      108330.238084
           ...
995    122488.588084
996    106194.188084
997    117353.804750
998    120137.854750
999    102666.004750
Name: date, Length: 1000, dtype: float64