<a href="https://colab.research.google.com/github/ajaykumar080286/feature_engineering/blob/main/3_api_to_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import requests

In [3]:
resposne=requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1")

In [8]:
res=resposne.json()

In [9]:
res1=res['results']

In [15]:
data=pd.DataFrame(res1)[["id","backdrop_path","release_date"]]

In [16]:
data.head()

    id                     backdrop_path release_date
0  278  /zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg   1994-09-23
1  238  /tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg   1972-03-14
2  240  /kGzFbGhp99zva6oZODW5atUtnqi.jpg   1974-12-20
3  424  /zb6fM1CX41D9rF9hdgclu0peUmy.jpg   1993-12-15
4  389  /w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg   1957-04-10

In [24]:
df = pd.DataFrame()
for i in range(1,429):
  resposne=requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}".format(i))
  res=resposne.json()
  res1=res['results']
  temp_df=pd.DataFrame(res1)[["id","backdrop_path","release_date"]]
  df = pd.concat([df, temp_df], ignore_index=True)

In [25]:
df

         id                     backdrop_path release_date
0       278  /zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg   1994-09-23
1       238  /tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg   1972-03-14
2       240  /kGzFbGhp99zva6oZODW5atUtnqi.jpg   1974-12-20
3       424  /zb6fM1CX41D9rF9hdgclu0peUmy.jpg   1993-12-15
4       389  /w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg   1957-04-10
...     ...                               ...          ...
8555  49730  /r4A5SQSGTfleodMm45w7MJgE2WF.jpg   2011-03-10
8556  13159  /kE3HQaJx9IuQCMIn3VVCXazXTea.jpg   2007-05-10
8557   1679  /xbKFQCZNK14gp9k6cFCwgp2OCtU.jpg   1955-04-24
8558   9096  /jsnzeDldCBScvH8ocuXG4ZK0Szn.jpg   1992-02-07
8559   7451  /2OHa6ukEq3Hce7Pc2kvu8wkmMFY.jpg   2002-08-09

[8560 rows x 3 columns]

In [26]:
df.shape

(8560, 3)

In [27]:
df.to_csv("movies.csv")